discover_investors_raw:
  description: >
    Find real LATAM investors aligned with NVIDIA Inception thesis focusing on AI/ML, robotics, edge computing.

    **FOCUS ON THESE VERIFIED LATAM INVESTORS:**

    1. **Kaszek Ventures** (Argentina/Brazil)
       - Website: https://www.kaszek.com
       - Focus: LatAm tech, AI, SaaS, Fintech

    2. **Monashees** (Brazil) 
       - Website: https://www.monashees.com.br
       - Focus: Early-stage AI, ML, SaaS, healthcare tech

    3. **ALLVP** (Mexico)
       - Website: https://www.allvp.vc
       - Focus: AI/ML, digital platforms, healthcare

    4. **Valor Capital Group** (Brazil/US)
       - Website: https://www.valorcapitalgroup.com
       - Focus: LatAm tech, AI, cross-border

    5. **SP Ventures** (Brazil)
       - Website: https://www.spventures.com.br
       - Focus: Corporate VC, innovation, tech

    **RULES:**
    - Research these 5 investors thoroughly
    - Do NOT add other investors beyond these 5
    - Do NOT research portfolio URLs yet - next task will handle that
    - Focus on validating their basic information (name, type, website, country, focus)

    Input thesis: "{thesis}"

  expected_output: >
    Information about the 5 verified LATAM investors listed above.
    Include their basic details but do NOT include portfolio URLs yet.

  agent: investor_research_agent


validate_investors:
  description: >
    **MISSION: USE REAL WEB SCRAPING TOOLS TO DISCOVER PORTFOLIO PAGES**

    For each of the 5 investors from the previous task, you must use the Web Scraper tool to actually visit their websites and find portfolio pages.

    **MANDATORY PROCESS FOR EACH INVESTOR:**

    1. **Use Web Scraper tool** to access their main website
    2. **Analyze the navigation menu** and footer links returned by the tool
    3. **Look for portfolio-related links** in the tool output
    4. **Use Portfolio Validator tool** to test potential portfolio URLs
    5. **Only include URLs that the Portfolio Validator confirms are valid**

    **STEP-BY-STEP INSTRUCTIONS:**

    For each investor (Kaszek, Monashees, ALLVP, Valor Capital, SP Ventures):

    1. **Run Web Scraper on their main website**:
       ```
       Web Scraper: https://www.example.com
       ```

    2. **Look for portfolio links in the output** - search for:
       - Portfolio / Portfólio
       - Companies / Empresas  
       - Investments / Inversiones
       - Startups
       - Our Companies

    3. **Test promising URLs with Portfolio Validator**:
       ```
       Portfolio Validator: https://www.example.com/portfolio
       ```

    4. **Only include URLs marked as ✅ VALID by the Portfolio Validator**

    **CRITICAL RULES:**
    - You MUST use the Web Scraper tool for each investor website
    - You MUST use the Portfolio Validator tool to verify any potential portfolio URLs
    - Only include portfolio_url if Portfolio Validator marks it as ✅ VALID
    - If no valid portfolio page is found after using the tools, set to null
    - Do NOT assume URLs work without using the Portfolio Validator

    **OUTPUT FORMAT:**
    {
      "investors": [
        {
          "name": "Kaszek Ventures",
          "type": "VC",
          "website": "https://www.kaszek.com",
          "hq_country": "AR", 
          "focus": "LatAm tech, AI, SaaS, Fintech",
          "portfolio_url": "validated URL or null"
        }
        // ... other investors
      ]
    }

  expected_output: >
    JSON with the 5 investors and their TOOL-VALIDATED portfolio URLs.
    Every portfolio_url must have been verified with the Portfolio Validator tool.

  agent: investor_validation_agent
  verbose: true


format_investors2json:
  description: >
    Format the validated investor data into the final JSON structure.
    
    **RULES:**
    1. Use the exact data from the validation task
    2. Do NOT modify any URLs or information  
    3. Do NOT add invented portfolio URLs
    4. Maintain the exact JSON structure
    5. Return only valid, parseable JSON

    **EXPECTED OUTPUT FORMAT:**
    {
      "investors": [
        {
          "name": "string",
          "type": "VC|CVC|Accelerator|Angel",
          "website": "string",
          "hq_country": "string",
          "focus": "string",
          "portfolio_url": "string or null"
        }
      ]
    }

  expected_output: >
    Clean JSON object with the validated investor data.

  agent: text2json_agent