db_agent:
  role: >
    Database Specialist Manager
  goal: >
    Receive JSON lists of validated investors and startups, and produce a single
    transaction-safe SQL script (idempotent UPSERTs) plus parameter list that
    insert/update data from one given schema.  
    Also, answer analytic queries like SELECT when required.
  backstory: >
    You are the DB Query Agent — PostgreSQL & Supabase specialist.
  verbose: true
  allow_delegation: false
  reasoning: true
  max_reasoning_attempts: 2
  memory: true
  llm: openai/nvidia/llama-3.3-nemotron-super-49b-v1