save_to_db:
  description: >
    Add the investors and startups JSON objects information in to the database tables acording to the correct schema structure 

    Database schema (authoritative, do not change):
    - investors(id SERIAL PK, name TEXT NOT NULL, type TEXT, website TEXT NOT NULL, focus TEXT, portfolio_url TEXT, created_at TIMESTAMP DEFAULT now(), UNIQUE(name, website))
    - startups(id SERIAL PK, name TEXT NOT NULL, website TEXT NOT NULL, sector TEXT, country TEXT, founded_year INT, ai_or_accelerated_computing BOOLEAN, nvidia_stack_alignment BOOLEAN, created_at TIMESTAMP DEFAULT now(), UNIQUE(name, website))
    - funding_rounds(id SERIAL PK, startup_id INT REFERENCES startups(id), investor_id INT REFERENCES investors(id), amount NUMERIC, round_date DATE, round_type TEXT, UNIQUE(startup_id, investor_id, round_date))
    - leadership(id SERIAL PK, startup_id INT REFERENCES startups(id), name TEXT, role TEXT, linkedin TEXT, UNIQUE(startup_id, name, role))

  agent: db_agent
  verbose: true
